# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Mod Properties
mod_id=jukeboxcustomdiscfix
mod_name=Jukebox Custom Disc Fix
mod_description=This mod fixes bug MC-260346 for discs modified using a resource pack, which causes custom music discs, when played in a jukebox, to be cut off when the vanilla disc would normally end.

version=0.2.0-26.2

# Publishing
maven_group=xyz.eclipseisoffline
archives_base_name=jukeboxcustomdiscfix

release_type=STABLE
modrinth_project_id=NtPNF0D7
github_repository=eclipseisoffline/jukeboxcustomdiscfix
git_branch=main
