modLoader="javafml"
loaderVersion="${neoforge_loader_version}"

license="GPLv3"
issueTrackerURL="https://github.com/eclipseisoffline/jukeboxcustomdiscfix/issues"

[[mods]]

modId="jukeboxcustomdiscfix"
version="${version}"

displayName="Jukebox Custom Disc Fix"
displayURL="https://modrinth.com/mod/jukebox-custom-disc-fix"
logoFile="assets/jukeboxcustomdiscfix/icon.png"

authors="eclipseisoffline"
description="This mod fixes bug MC-260346, which causes custom music discs, when played in a jukebox, to be cut off when the vanilla disc would normally end."

displayTest="IGNORE_SERVER_VERSION"

[[mixins]]
config="jukeboxcustomdiscfix.mixins.json"

[[dependencies.jukeboxcustomdiscfix]]
modId="minecraft"
type="required"

versionRange="${neoforge_supported_versions}"
ordering="NONE"
side="SERVER"
